"""
Airport Code and City Resolver
Maps common city names (English, Chinese, local aliases) to 3-letter IATA airport codes.
"""
from typing import Optional, Dict

# Common City to Primary Airport IATA Mappings
CITY_AIRPORT_MAP: Dict[str, str] = {
    # Vietnam
    "hanoi": "HAN",
    "河内": "HAN",
    "hà nội": "HAN",
    "ho chi minh": "SGN",
    "ho chi minh city": "SGN",
    "saigon": "SGN",
    "胡志明": "SGN",
    "胡志明市": "SGN",
    "西贡": "SGN",
    "da nang": "DAD",
    "danang": "DAD",
    "岘港": "DAD",
    "nha trang": "CXR",
    "芽庄": "CXR",
    "phu quoc": "PQC",
    "富国岛": "PQC",
    "hai phong": "HPH",
    "海防": "HPH",
    "can tho": "VCA",
    "芹苴": "VCA",
    "hue": "HUI",
    "顺化": "HUI",

    # China - Guangxi & South China
    "guilin": "KWL",
    "桂林": "KWL",
    "nanning": "NNG",
    "南宁": "NNG",
    "guangzhou": "CAN",
    "广州": "CAN",
    "shenzhen": "SZX",
    "深圳": "SZX",
    "hong kong": "HKG",
    "hongkong": "HKG",
    "香港": "HKG",
    "macau": "MFM",
    "macao": "MFM",
    "澳门": "MFM",
    "zhuhai": "ZUH",
    "珠海": "ZUH",
    "haikou": "HAK",
    "海口": "HAK",
    "sanya": "SYX",
    "三亚": "SYX",

    # China - Major Hubs
    "shanghai": "PVG",
    "上海": "PVG",
    "pudong": "PVG",
    "浦东": "PVG",
    "hongqiao": "SHA",
    "虹桥": "SHA",
    "beijing": "PEK",
    "北京": "PEK",
    "daxing": "PKX",
    "大兴": "PKX",
    "capital": "PEK",
    "chengdu": "TFU",
    "成都": "TFU",
    "tianfu": "TFU",
    "天府": "TFU",
    "shuangliu": "CTU",
    "双流": "CTU",
    "chongqing": "CKG",
    "重庆": "CKG",
    "kunming": "KMG",
    "昆明": "KMG",
    "xiamen": "XMN",
    "厦门": "XMN",
    "fuzhou": "FOC",
    "福州": "FOC",
    "hangzhou": "HGH",
    "杭州": "HGH",
    "nanjing": "NKG",
    "南京": "NKG",
    "wuhan": "WUH",
    "武汉": "WUH",
    "changsha": "CSX",
    "长沙": "CSX",
    "xian": "XIY",
    "xi'an": "XIY",
    "西安": "XIY",
    "zhengzhou": "CGO",
    "郑州": "CGO",
    "qingdao": "TAO",
    "青岛": "TAO",
    "jinan": "TNA",
    "济南": "TNA",
    "tianjin": "TSN",
    "天津": "TSN",
    "dalian": "DLC",
    "大连": "DLC",
    "shenyang": "SHE",
    "沈阳": "SHE",
    "harbin": "HRB",
    "哈尔滨": "HRB",
    "urumqi": "URC",
    "乌鲁木齐": "URC",
    "guiyang": "KWE",
    "贵阳": "KWE",
    "taipei": "TPE",
    "台北": "TPE",
    "kaohsiung": "KHH",
    "高雄": "KHH",

    # Southeast Asia
    "bangkok": "BKK",
    "曼谷": "BKK",
    "suvarnabhumi": "BKK",
    "don mueang": "DMK",
    "廊曼": "DMK",
    "chiang mai": "CNX",
    "清迈": "CNX",
    "phuket": "HKT",
    "普吉岛": "HKT",
    "普吉": "HKT",
    "singapore": "SIN",
    "新加坡": "SIN",
    "changi": "SIN",
    "kuala lumpur": "KUL",
    "吉隆坡": "KUL",
    "penang": "PEN",
    "槟城": "PEN",
    "jakarta": "CGK",
    "雅加达": "CGK",
    "bali": "DPS",
    "登巴萨": "DPS",
    "巴厘岛": "DPS",
    "manila": "MNL",
    "马尼拉": "MNL",
    "cebu": "CEB",
    "宿务": "CEB",
    "phnom penh": "PNH",
    "金边": "PNH",
    "siem reap": "SAI",
    "暹粒": "SAI",
    "vientiane": "VTE",
    "万象": "VTE",
    "luang prabang": "LPQ",
    "琅勃拉邦": "LPQ",
    "yangon": "RGN",
    "仰光": "RGN",

    # East Asia
    "tokyo": "TYO",
    "东京": "TYO",
    "haneda": "HND",
    "羽田": "HND",
    "narita": "NRT",
    "成田": "NRT",
    "osaka": "KIX",
    "大阪": "KIX",
    "kansai": "KIX",
    "关西": "KIX",
    "kyoto": "KIX",
    "京都": "KIX",
    "fukuoka": "FUK",
    "福冈": "FUK",
    "sapporo": "CTS",
    "札幌": "CTS",
    "seoul": "ICN",
    "首尔": "ICN",
    "incheon": "ICN",
    "仁川": "ICN",
    "gimpo": "GMP",
    "金浦": "GMP",
    "busan": "PUS",
    "釜山": "PUS",
    "jeju": "CJU",
    "济州岛": "CJU",

    # Global Hubs
    "london": "LHR",
    "伦敦": "LHR",
    "heathrow": "LHR",
    "paris": "CDG",
    "巴黎": "CDG",
    "frankfurt": "FRA",
    "法兰克福": "FRA",
    "amsterdam": "AMS",
    "阿姆斯特丹": "AMS",
    "dubai": "DXB",
    "迪拜": "DXB",
    "doha": "DOH",
    "多哈": "DOH",
    "new york": "JFK",
    "纽约": "JFK",
    "los angeles": "LAX",
    "洛杉矶": "LAX",
    "san francisco": "SFO",
    "旧金山": "SFO",
    "seattle": "SEA",
    "西雅图": "SEA",
    "sydney": "SYD",
    "悉尼": "SYD",
    "melbourne": "MEL",
    "墨尔本": "MEL",
}

def resolve_airport(input_str: str) -> str:
    """
    Resolve a city name, airport alias, or IATA code to a standardized 3-letter IATA code.
    If the input is already a 3-letter uppercase string, returns it directly.
    """
    if not input_str:
        return ""
    
    clean_str = input_str.strip()
    
    # If 3 letters without spaces/CJK, treat as candidate IATA code
    if len(clean_str) == 3 and clean_str.isalpha() and clean_str.isascii():
        return clean_str.upper()
    
    # Search normalized map
    norm_key = clean_str.lower()
    if norm_key in CITY_AIRPORT_MAP:
        return CITY_AIRPORT_MAP[norm_key]
    
    # Fallback: uppercase string
    return clean_str.upper()
